server:
  port: 8080
  servlet:
    context-path: "/ho-api"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root1
    password: 1711_Nguyen
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
mybatis:
  type-aliases-package: classpath*:cn.mafangui.hotel.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml

logging:
  file: application.log
  level:
    root: DEBUG
    org.springframework: WARN
    stackjava.com.sblogging.service: INFO
